spring:
  profiles:
    active: dev
  application:
    name: rainbow-web
  # 时间出参格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  # 时间入参格式
  mvc:
    format:
      date-time: yyyy-MM-dd
  servlet:
    multipart:
      enabled: true # 开启文件上传
      max-file-size: 10MB # 限制最大文件
  # sa-token配置
  sa-token:
    # token名称（同时也是cookie名称）
    token-name: Authorization
    # token有效期，单位s 默认30天
    timeout: 2592000
    # 在多人登录同一账号时，是否共享会话（为true时共用一个，为false时新登录挤掉旧登录）
    is-share: false
    # 是否在cookie读取不到token时，继续从请求header里继续尝试读取
    is-read-head: true
    #  是否在header读取不到token时，继续从请求题参数里继续尝试读取
    is-read-body: true
    # 是否在初始化配置时打印版本字符画
    is-v: true

# 文件管理系统
minio:
  url: http://ENC(qvo9Fu8+aKZM6oL5L7HeMvJmF9Z5iJfbHUhdsMBxLVCNUDi06nwayc8/45xg1oTt):9090 # minio 服务地址
  accessKey: ENC(WHazqLRMdBqVPAGvi6LtaN43f+04tnHGhILxjDw5BCkX1TIkMpixjwtxOPM54/uW) # 账号
  secretKey: ENC(WHazqLRMdBqVPAGvi6LtaN43f+04tnHGhILxjDw5BCkX1TIkMpixjwtxOPM54/uW) # 密码
  bucketName: ${spring.application.name} # 桶名称

# 验证码设置
aj:
  captcha:
    type: default
    water-mark: &#114;&#97;&#105;&#110;&#98;&#111;&#119;&#45;&#119;&#101;&#98
    jigsaw: classpath:images/jigsaw
    pic-click: classpath:images/pic-click
    interference-options: 1
    cache-type: redis
